[project]
name = "bof-text"
description = "Command line tool for editing Breath of Fire III and IV text sections"
readme = "README.md"
license = {file = "LICENSE.md"}
dynamic = ["version"]

[project.scripts]
bof-text = "bof_text_editor:main"